# Generated by Django 5.2.10 on 2026-01-13 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0002_rename_full_name_profile_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='name',
            new_name='full_name',
        ),
    ]
