# Generated by Django 5.2.10 on 2026-01-13 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='whatsapp_number',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
    ]
