# Generated by Django 5.2.10 on 2026-01-13 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
    ]
